### ISSUE TITLE
from ctrajoptpy import * ImportError: No module named ctrajoptpy

### ISSUE THREAD

**Issue by lakshmip001** [joschu/trajopt#24]
I installed trajoptpy, but when I try to run the program it results in the above error.
File "/home/lakshmi/git/trajopt/trajoptpy/__init__.py", line 1, in <module>
    from ctrajoptpy import *
ImportError: No module named ctrajoptpy

**Comment by lakshmip001** [comment]
sourcing the build directory in bash solved this problem.

**Comment by WHGang** [comment]
I have the same problem as you. How did you do it? Which command to use?

**Comment by daphnechen** [comment]
From the documentation:

"You need to set your PYTHONPATH to call trajopt from python. Add the following two paths to your PYTHONPATH"
