### ISSUE TITLE
how to solve errors while running ctest

### ISSUE THREAD

**Issue by lakshmip001** [joschu/trajopt#34]
Test project /home/lakshmi/tes_traj/trajopt/build
      Start  1: arm_to_joint_target.py
 1/10 Test  #1: arm_to_joint_target.py .............   Passed    2.87 sec
      Start  2: arm_to_cart_target.py
 2/10 Test  #2: arm_to_cart_target.py ..............***Failed   11.83 sec
      Start  3: fullbody_plan.py
 3/10 Test  #3: fullbody_plan.py ...................   Passed    3.71 sec
      Start  4: position_base.py
 4/10 Test  #4: position_base.py ...................   Passed    1.94 sec
      Start  5: this_side_up.py
 5/10 Test  #5: this_side_up.py ....................***Failed   11.36 sec
      Start  6: arm_to_cart_target_position_only
 6/10 Test  #6: arm_to_cart_target_position_only ...***Failed   11.55 sec
      Start  7: sco-unit
 7/10 Test  #7: sco-unit ...........................   Passed    0.04 sec
      Start  8: collision-checker-unit
 8/10 Test  #8: collision-checker-unit .............   Passed    0.06 sec
      Start  9: planning-unit
 9/10 Test  #9: planning-unit ......................   Passed    1.70 sec
      Start 10: cast-cost-unit
10/10 Test #10: cast-cost-unit .....................   Passed    0.06 sec

70% tests passed, 3 tests failed out of 10

Total Test time (real) =  45.11 sec

The following tests FAILED:
	  2 - arm_to_cart_target.py (Failed)
	  5 - this_side_up.py (Failed)
	  6 - arm_to_cart_target_position_only (Failed)
Errors while running CTest

**Comment by EdsterG** [comment]
Run the tests with the `--verbose` flag.

**Comment by ruiaisun** [comment]
@EdsterG Do you know how to solve this error?
```
Test project /home/geriatronics/Projects/trajopt/build
      Start  1: arm_to_joint_target.py
 1/10 Test  #1: arm_to_joint_target.py .............***Exception: Numerical  0.28 sec
      Start  2: arm_to_cart_target.py
 2/10 Test  #2: arm_to_cart_target.py ..............***Exception: Numerical  0.28 sec
      Start  3: fullbody_plan.py
 3/10 Test  #3: fullbody_plan.py ...................***Exception: Numerical  0.28 sec
      Start  4: position_base.py
 4/10 Test  #4: position_base.py ...................***Failed    0.03 sec
      Start  5: this_side_up.py
 5/10 Test  #5: this_side_up.py ....................***Exception: Numerical  0.28 sec
      Start  6: arm_to_cart_target_position_only
 6/10 Test  #6: arm_to_cart_target_position_only ...***Exception: Numerical  0.28 sec
      Start  7: sco-unit
 7/10 Test  #7: sco-unit ...........................   Passed    0.03 sec
      Start  8: collision-checker-unit
 8/10 Test  #8: collision-checker-unit .............   Passed    0.03 sec
      Start  9: planning-unit
 9/10 Test  #9: planning-unit ......................   Passed    0.95 sec
      Start 10: cast-cost-unit
10/10 Test #10: cast-cost-unit .....................   Passed    0.02 sec

40% tests passed, 6 tests failed out of 10

Total Test time (real) =   2.45 sec

The following tests FAILED:
	  1 - arm_to_joint_target.py (NUMERICAL)
	  2 - arm_to_cart_target.py (NUMERICAL)
	  3 - fullbody_plan.py (NUMERICAL)
	  4 - position_base.py (Failed)
	  5 - this_side_up.py (NUMERICAL)
	  6 - arm_to_cart_target_position_only (NUMERICAL)
Errors while running CTest
Output from these tests are in: /home/geriatronics/Projects/trajopt/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
when I run 'python arm_to_joint_target.py' in the folder /python_examples, ithe error just like:
```
You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to INFO
Traceback (most recent call last):
  File "arm_to_joint_target.py", line 7, in <module>
    import trajoptpy
  File "/home/geriatronics/Projects/trajopt/trajoptpy/__init__.py", line 1, in <module>
    from ctrajoptpy import *
ImportError: dynamic module does not define init function (initctrajoptpy)
Floating point exception (core dumped)
```
