### ISSUE TITLE
Cannot compile trajopt - OpenRAVE compilation error

### ISSUE THREAD

**Issue by ddirckx** [joschu/trajopt#46]
Hi, 
I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error 

[ 55%] Built target osgviewer
Scanning dependencies of target trajopt
[ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o
[ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o
[ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o
[ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o
[ 64%] Linking CXX executable ../../../bin/sco-unit
[ 64%] Built target sco-unit
[ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o
[ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o
[ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o
[ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o
[ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o
[ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o
/home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’:
/home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptr<OpenRAVE::UserData>}’ to ‘bool’ in initialization
   bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh");
                                                                 ^
src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed
make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed
make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
- OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
- OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
- Boost: version 1.69.0 (also gave the error with version 1.58.0)

Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.

Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!

**Comment by HangX-Ma** [comment]
https://wiki.khoury.northeastern.edu/display/HELPINGHANDS/UR5+in+Ubuntu+18.04

**Comment by zhoucheng0818** [comment]
> Hi, I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error
> 
> [ 55%] Built target osgviewer Scanning dependencies of target trajopt [ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o [ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o [ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o [ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o [ 64%] Linking CXX executable ../../../bin/sco-unit [ 64%] Built target sco-unit [ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o [ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o [ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o [ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o [ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o [ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’: /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptrOpenRAVE::UserData}’ to ‘bool’ in initialization bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh"); ^ src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2 Makefile:94: recipe for target 'all' failed make: *** [all] Error 2
> 
> I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
> 
> * OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
> * OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
> * Boost: version 1.69.0 (also gave the error with version 1.58.0)
> 
> Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.
> 
> Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!

Hello,  I have the same problem about this. How can I solve it?

**Comment by HangX-Ma** [comment]
> > Hi, I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error
> > [ 55%] Built target osgviewer Scanning dependencies of target trajopt [ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o [ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o [ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o [ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o [ 64%] Linking CXX executable ../../../bin/sco-unit [ 64%] Built target sco-unit [ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o [ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o [ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o [ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o [ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o [ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’: /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptrOpenRAVE::UserData}’ to ‘bool’ in initialization bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh"); ^ src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2 Makefile:94: recipe for target 'all' failed make: *** [all] Error 2
> > I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
> > 
> > * OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
> > * OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
> > * Boost: version 1.69.0 (also gave the error with version 1.58.0)
> > 
> > Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.
> > Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!
> 
> Hello, I have the same problem about this. How can I solve it?

My previous comment, which contains a website address, gives some cases that may help you.

**Comment by josyulakrishna** [comment]
> > > Hi, I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error
> > > [ 55%] Built target osgviewer Scanning dependencies of target trajopt [ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o [ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o [ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o [ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o [ 64%] Linking CXX executable ../../../bin/sco-unit [ 64%] Built target sco-unit [ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o [ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o [ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o [ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o [ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o [ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’: /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptrOpenRAVE::UserData}’ to ‘bool’ in initialization bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh"); ^ src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2 Makefile:94: recipe for target 'all' failed make: *** [all] Error 2
> > > I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
> > > 
> > > * OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
> > > * OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
> > > * Boost: version 1.69.0 (also gave the error with version 1.58.0)
> > > 
> > > Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.
> > > Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!
> > 
> > 
> > Hello, I have the same problem about this. How can I solve it?
> 
> My previous comment, which contains a website address, gives some cases that may help you.

Hi that link is now blocked with a login and password. Could you please let me know what changes you've made?

**Comment by HangX-Ma** [comment]
> > > > Hi, I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error
> > > > [ 55%] Built target osgviewer Scanning dependencies of target trajopt [ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o [ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o [ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o [ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o [ 64%] Linking CXX executable ../../../bin/sco-unit [ 64%] Built target sco-unit [ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o [ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o [ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o [ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o [ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o [ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’: /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptrOpenRAVE::UserData}’ to ‘bool’ in initialization bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh"); ^ src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2 Makefile:94: recipe for target 'all' failed make: *** [all] Error 2
> > > > I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
> > > > 
> > > > * OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
> > > > * OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
> > > > * Boost: version 1.69.0 (also gave the error with version 1.58.0)
> > > > 
> > > > Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.
> > > > Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!
> > > 
> > > 
> > > Hello, I have the same problem about this. How can I solve it?
> > 
> > 
> > My previous comment, which contains a website address, gives some cases that may help you.
> 
> Hi that link is now blocked with a login and password. Could you please let me know what changes you've made?

Sorry I have stopped the related research two years ago. I can not recall too much details. But this link <https://github.com/crigroup/openrave-installation> may help you solve your problem. I once use this automation tool to assist me with installing the essential tools you have mentioned above (Of course I also tried **robots.uc3m.es** provided methods). Have a nice day~ 😃

**Comment by josyulakrishna** [comment]
Ah I see, Thank you for taking time to respond!  : ) 
 
> > > > > Hi, I am trying to install TrajOpt on Ubuntu 18.04 but I get the following compilation error
> > > > > [ 55%] Built target osgviewer Scanning dependencies of target trajopt [ 57%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/traj_plotter.cpp.o [ 58%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/trajectory_costs.cpp.o [ 60%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/kinematic_terms.cpp.o [ 62%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/collision_terms.cpp.o [ 64%] Linking CXX executable ../../../bin/sco-unit [ 64%] Built target sco-unit [ 66%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/json_marshal.cpp.o [ 67%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/problem_description.cpp.o [ 69%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o [ 71%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/configuration_space.cpp.o [ 73%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/utils.cpp.o [ 75%] Building CXX object src/trajopt/CMakeFiles/trajopt.dir/rave_utils.cpp.o /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp: In member function ‘void {anonymous}::BulletCollisionChecker::AddKinBody(const KinBodyPtr&)’: /home/driesdirckx/repos/trajopt/src/trajopt/bullet_collision_checker.cpp:543:65: error: cannot convert ‘OpenRAVE::UserDataPtr {aka boost::shared_ptrOpenRAVE::UserData}’ to ‘bool’ in initialization bool useTrimesh = trajopt::GetUserData(*body, "bt_use_trimesh"); ^ src/trajopt/CMakeFiles/trajopt.dir/build.make:206: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o' failed make[2]: *** [src/trajopt/CMakeFiles/trajopt.dir/bullet_collision_checker.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:443: recipe for target 'src/trajopt/CMakeFiles/trajopt.dir/all' failed make[1]: *** [src/trajopt/CMakeFiles/trajopt.dir/all] Error 2 Makefile:94: recipe for target 'all' failed make: *** [all] Error 2
> > > > > I first build OpenRave after which I build OpenSceneGraph and then I try to build TrajOpt from this repository. I already tried out the different solutions offered in issue #20 .I used the following versions and installation procedures for OpenRave and OSG, ..:
> > > > > 
> > > > > * OpenRAVE 0.9.0: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html
> > > > > * OpenSceneGraph 3.4.1: http://robots.uc3m.es/gitbook-installation-guides/install-openrave.html OR https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.html?fbclid=IwAR1t8Rd0i58b_F4uEddnrbqAZYG7NJOQEktZhOMo53EKiJVotBWDTULrKng
> > > > > * Boost: version 1.69.0 (also gave the error with version 1.58.0)
> > > > > 
> > > > > Both procedure for installing OpenRAVE and OSG give the same error if I try to compile TrajOpt. Installing the flexible collision library FCL has no effect on the error that I get.
> > > > > Do you have any idea how I can fix this and successfully build TrajOpt ? Thanks in advance!
> > > > 
> > > > 
> > > > Hello, I have the same problem about this. How can I solve it?
> > > 
> > > 
> > > My previous comment, which contains a website address, gives some cases that may help you.
> > 
> > 
> > Hi that link is now blocked with a login and password. Could you please let me know what changes you've made?
> 
> Sorry I have stopped the related research two years ago. I can not recall too much details. But this link https://github.com/crigroup/openrave-installation may help you solve your problem. I once use this automation tool to assist me with installing the essential tools you have mentioned above (Of course I also tried **robots.uc3m.es** provided methods). Have a nice day~ smiley
